### ISSUE TITLE
Color of contact us icon

### ISSUE THREAD

**Issue by rishabhthakur11** [rishabhthakur11/KartikPhotoStudio#5]
change the colour of the icon of (contact us) bell  to a suitable colour so that it looks good on scrolling.Light grey colour is preferred in my opinion.

<img width="1440" alt="Screenshot 2021-02-19 at 11 03 41 AM" src="https://user-images.githubusercontent.com/74073486/108462320-6d5cd180-72a2-11eb-8db8-7d580b8917a9.png">

**Comment by Priyaraj17** [comment]
I would like to work on this issue. Please assign it to me

**Comment by rishabhthakur11** [comment]
ya sure u can solve this

**Comment by rishabhthakur11** [comment]
colour of icon changed
